### ISSUE TITLE
Set RTL mode via Story parameter

### ISSUE THREAD

**Issue by dozortsev** [unindented/storybook-addon-rtl#16]
Hey

from `README.md`

> **Note**: You can force a story to show in right-to-left mode by adding the query parameter `direction=rtl`.

but we can't make this work...

by "query parameter" do you mean [Story parameters](https://storybook.js.org/docs/react/writing-stories/parameters)?

in `.storybook/preview.js` we have:

```js
import { initializeRTL } from 'storybook-addon-rtl';
...

initializeRTL();

export const parameters = {
  ...
  direction: 'rtl',

  ...
}
```

and this should be enough, right? but when Storybook launches it suppose to be running in RtL but it's not

<img width="1361" alt="Screen Shot 2021-08-25 at 6 00 52 PM" src="https://user-images.githubusercontent.com/4015628/130815251-b1393d8a-ccdc-4168-a2b3-8c325055dffe.png">

we use Storybook 6 (`"@storybook/react": "^6.3.7",`) here is little PR with all the details https://github.com/transferwise/neptune-web/pull/1061/files

**Comment by dozortsev** [comment]
I don't think this is a bug in the addon as I can see that you read this value [here](https://github.com/unindented/storybook-addon-rtl/blob/master/src/containers/RTLPanel/index.js#L12) maybe we just missing something, could you please help?

cc @literalpie @unindented

**Comment by unindented** [comment]
@dozortsev what version of Storybook are you using?

When I wrote this library, Storybook was on v3. Query parameters worked fine back then. It's highly likely something has changed in their APIs in the most recent versions that broke this... Feel free to investigate and report back.

@literalpie do you know anything about this?

**Comment by literalpie** [comment]
I think the readme, and the line of code that you linked to are related to [queryParams](https://storybook.js.org/docs/react/addons/addons-api#apisetqueryparams) from the addon API, not the story parameters you mention in the original question. 

I think it would make sense to remove mention of queryParams from the readme and add support for story parameters like @dozortsev is trying to do. I will look into this.

**Comment by literalpie** [comment]
This won't be as simple as I originally thought, but I think I have a good start. Hopefully I'll have this done in a week or so

**Comment by unindented** [comment]
No rush, this is all volunteer work you're doing! Thank you so much!
