### ISSUE TITLE
Placement of `dir` attribute

### ISSUE THREAD

**Issue by skitterm** [unindented/storybook-addon-rtl#2]
Thanks for this addon.

I've noticed that when I toggle the `rtl` switch in storybook, the `dir="rtl"` attribute gets added to the `body` tag.

Looks like the [W3C](https://www.w3.org/International/questions/qa-html-dir#quickanswer) recommends that the `dir` attrubute be put on the `html` tag instead. Could it be placed there instead?

**Comment by ronanmulvaney** [comment]
I have the same requirement if this was possible to change/add. Thanks.

**Comment by dr3** [comment]
Hey @unindented, any updates on if this issue can be addressed? Us over in https://github.com/bbc/psammead would be happy to make a PR if you would like?

**Comment by unindented** [comment]
@dr3 please do!
