### ISSUE TITLE
Storybook v7

### ISSUE THREAD

**Issue by literalpie** [unindented/storybook-addon-rtl#35]
Storybook 7.0 will include many breaking changes. I don't know if it will be possible to support both 6.x and 7.x in the addon, but I'm guessing we'll need to do a breaking change version bump.

For now, I've made a `storybook-v7` branch with the changes needed so far to continue working.

**Comment by markpalfreeman** [comment]
+1  we're starting to use Storybook v7 so having a published version (even if beta) would be great!

**Comment by literalpie** [comment]
Release 0.4.4 should support both storybook 6.5 and 7.0!
