### ISSUE TITLE
RTL button are display on the wrong place

### ISSUE THREAD

**Issue by Romakita** [unindented/storybook-addon-rtl#7]
Hello all,

I use the storybook v5 and I tried to add your addon. It works but his rendering is wrong. The button appear on every panel.

Here a screen:
<img width="520" alt="Capture d’écran 2019-07-17 à 10 52 38" src="https://user-images.githubusercontent.com/1763311/61361671-1e0e1e00-a881-11e9-9a00-a942521e64f3.png">

Thanks in advance for your help
See you :)

**Comment by literalpie** [comment]
This is old and I'm not seeing this with the latest versions of storybook. Please reopen with more specific steps to reproduce if this is still an issue.
